language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - coverage run --parallel-mode --source=plugins -m unittest discover plugins/tests "*_test.py"
  - coverage run --parallel-mode --source api django_foodbot/manage.py test django_foodbot
  - coverage combine

after_success:
  coveralls

notifications:
    slack: food-review:iP55LweubU8UOBgu9e0cTeED
